server:
  port: 8085
  error:
    whitelabel:
      enabled: false
    path: /error


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-management-service
          predicates:
            - Path=/accounts/**
          uri: account-management-service:8082
        - id: customer-management-service
          predicates:
            - Path=/customers/**
          uri: customer-management-service:8081
