server:
  port: 8085
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-management-service
          predicates:
            - Path: /accounts/**
          uri: http://account-management-service:8082
        - id: customer-management-service
          predicates:
            - Path: /customers/**
          uri: http://customer-management-service:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
