server:
  port: 8085
  error:
    whitelabel:
      enabled: false
    path: /error


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-management-service
          predicates:
            - Path=/accounts/**
          uri: account-management-service:8082
        - id: customer-management-service
          predicates:
            - Path=/customers/**
          uri: customer-management-service:8081


SSL_TLS_configuration:
  server:
    ssl:
      key-store: "classpath:keystore.p12"
      key-store-password: "password"
      trust-store: "classpath:truststore.p12"
      trust-store-password: "password"
